
GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/65d8da23601564a1a93bdc07

###


GET http://localhost:3000/api/tracks


###


GET http://localhost:3000/api/storage


###

POST http://localhost:3000/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpg

< ./img.jpg
--Boundry--

###

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json

{
    "dato": "basura",
    "name": "cryptobro",
    "album": "cuentame",
    "cover": "http://yyy.com",
    "artist": {
        "name": "joe",
        "nickname": "parecetrue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0444456789abcdef01234567"
  
}

###

###

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
    "dato": "basura",
    "name": "tetvalidaotr",
    "album": "validate",
    "cover": "",
    "artist": {
        "name": "val",
        "nickname": "deepfuckinvalue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":3
    },
    "mediaId": "0444456789abcdef01234567"
  
}

###
// API TEST POST
POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "dato": "basura",
    "name": "deletetetst",
    "album": "album",
    "cover": "cover",
    "artist": {
        "name": "val",
        "nickname": "alue",
        "nationality": "VAR"
    },
    "duration": {
        "start":1,
        "end":3
    },
    "mediaId": "0444456789abcdef01222222"
  
}

###
// API TEST POST MATCHED DATA REQ(BODY)
POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "dato": "basura",
    "name": "tetvalidaotr",
    "album": "validate",
    "cover": "TEST",
    "artist": {
        "name": "val",
        "nickname": "deepfuckinvalue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":3
    },
    "mediaId": "0444456789abcdef01234567"
  
}

###
// GET DE 1 ITEM /:id(name)
GET http://localhost:3000/api/tracks/cryptobro HTTP/1.1
api_key: Api-publica-123




###
// GET DE 1 ITEM /:id(id)
GET http://localhost:3000/api/tracks/65d46d39c7f1c3ab344362c0 HTTP/1.1
api_key: Api-publica-123



###
// DELETE DE 1 ITEM /:id(name)
DELETE http://localhost:3000/api/tracks/65e1d41fe2f8c22373d304fc HTTP/1.1


###
// API TEST UPDATE
PUT http://localhost:3000/api/tracks/65dda4006c052867817cf308 HTTP/1.1
Content-Type: application/json

{
    "name": "UPDATE",
    "album": "CHANGE",
    "cover": "TEST",
    "artist": {
        "name": "val",
        "nickname": "deepfuckinvalue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":3
    },
    "mediaId": "0444456789abcdef01234567"
  
}

###
// API TEST POST MATCHED DATA REQ(BODY)
PUT http://localhost:3000/api/tracks/65d46d39c7f1c3ab344362c0 HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name": "UPDATE",
    "album": "CHANGE",
    "cover": "TEST",
    "artist": {
        "name": "val",
        "nickname": "deepfuckinvalue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":3
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "bluefroh",
    "age": 22,
    "email": "froggy@gmail.com",
    "password": "passwordthefrog"
  
}

###

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "froggy@gmail.com",
    "password": "passwordthefrog1111"
  
}

###

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "blue",
    "age": 22,
    "email": "blueworld@gmail.com",
    "password": "passwordtheworld"
  
}

###