
GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/65d8da23601564a1a93bdc07

###


GET http://localhost:3000/api/tracks


###


GET http://localhost:3000/api/storage


###

POST http://localhost:3000/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpg

< ./img.jpg
--Boundry--

###

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json

{
    "dato": "basura",
    "name": "cryptobro",
    "album": "cuentame",
    "cover": "http://yyy.com",
    "artist": {
        "name": "joe",
        "nickname": "parecetrue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0444456789abcdef01234567"
  
}

###

###

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
    "dato": "basura",
    "name": "tetvalidaotr",
    "album": "validate",
    "cover": "",
    "artist": {
        "name": "val",
        "nickname": "deepfuckinvalue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":3
    },
    "mediaId": "0444456789abcdef01234567"
  
}

###
// API TEST POST
POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "dato": "basura",
    "name": "deletetetst",
    "album": "album",
    "cover": "cover",
    "artist": {
        "name": "val",
        "nickname": "alue",
        "nationality": "VAR"
    },
    "duration": {
        "start":1,
        "end":3
    },
    "mediaId": "0444456789abcdef01222222"
  
}

###
// API TEST POST MATCHED DATA REQ(BODY)
POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "dato": "basura",
    "name": "tetvalidaotr",
    "album": "validate",
    "cover": "TEST",
    "artist": {
        "name": "val",
        "nickname": "deepfuckinvalue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":3
    },
    "mediaId": "0444456789abcdef01234567"
  
}

###
// GET DE 1 ITEM /:id(name)
GET http://localhost:3000/api/tracks/cryptobro HTTP/1.1
api_key: Api-publica-123




###
// GET DE 1 ITEM /:id(id)
GET http://localhost:3000/api/tracks/65d46d39c7f1c3ab344362c0 HTTP/1.1
api_key: Api-publica-123



###
// DELETE DE 1 ITEM /:id(name)
DELETE http://localhost:3000/api/tracks/65e1d41fe2f8c22373d304fc HTTP/1.1


###
// API TEST UPDATE
PUT http://localhost:3000/api/tracks/65dda4006c052867817cf308 HTTP/1.1
Content-Type: application/json

{
    "name": "UPDATE",
    "album": "CHANGE",
    "cover": "TEST",
    "artist": {
        "name": "val",
        "nickname": "deepfuckinvalue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":3
    },
    "mediaId": "0444456789abcdef01234567"
  
}

###
// API TEST POST MATCHED DATA REQ(BODY)
PUT http://localhost:3000/api/tracks/65d46d39c7f1c3ab344362c0 HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name": "UPDATE",
    "album": "CHANGE",
    "cover": "TEST",
    "artist": {
        "name": "val",
        "nickname": "deepfuckinvalue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":3
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "bluefroh",
    "age": 22,
    "email": "froggy@gmail.com",
    "password": "passwordthefrog"
  
}

###

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "froggy@gmail.com",
    "password": "passwordthefrog"
  
}

###

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "green",
    "age": 22,
    "email": "green@gmail.com",
    "password": "passwordtheworld"
  
}

###
###

GET http://localhost:3000/api/tracks HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWU2ZGM3YWZmNGY5MjQzNGUwODAzOTciLCJlbWFpbCI6ImZyb2dneUBnbWFpbC5jb20iLCJpYXQiOjE3MTAyMzEwODEsImV4cCI6MTcxMDIzODI4MX0.mEhahLv6GZoG0TSPL1O7KT0wFAS-1J7dAM4NZza_cjQ 


###
// TEST DE LOGINUSER Y POST ADMIN
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "blue@gmail.com",
    "password": "passwordtheworld"
}

###
//LOGIN
###
// TEST DE LOGINUSER Y POST ADMIN
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "purple",
    "age": 22,
    "email": "purple@gmail.com",
    "password": "passwordtheworld",
    "role":"admin"
  
}

###
###

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYwMTNkZTJlZjljZjA2MjJlY2Y2OGEiLCJlbWFpbCI6ImJsdWVAZ21haWwuY29tIiwiaWF0IjoxNzEwMjMzMDIwLCJleHAiOjE3MTAyNDAyMjB9.Lv9zkyC4vd4j1gXdk_khQ8LMDEVMdvF6uDBaJKLXe88

{
    "dato": "antoniiito",
    "name": "antoniiitooss",
    "album": "elveranoloco",
    "cover": "antonin",
    "artist": {
        "name": "valorrrr",
        "nickname": "deepfuckinvalue",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":3
    },
    "mediaId": "3344456789abcdef01234567"
  
}

###65e6deb3ff4f92434e08039c
PUT http://localhost:3000/api/auth/65e6deb3ff4f92434e08039c HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYwMTNkZTJlZjljZjA2MjJlY2Y2OGEiLCJlbWFpbCI6ImJsdWVAZ21haWwuY29tIiwiaWF0IjoxNzEwMjMzMDIwLCJleHAiOjE3MTAyNDAyMjB9.Lv9zkyC4vd4j1gXdk_khQ8LMDEVMdvF6uDBaJKLXe88

{
    "role":"admin"
}

###
PUT http://localhost:3000/api/auth/update/green@gmail.com HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYwMTNkZTJlZjljZjA2MjJlY2Y2OGEiLCJlbWFpbCI6ImJsdWVAZ21haWwuY29tIiwiaWF0IjoxNzEwMjM1NzA5LCJleHAiOjE3MTAyNDI5MDl9.MHXhXrK7TIQDOpiuMCFdBWcyejpnwkGJjvyl9Yq-aS8

{
    "role":"admin"
}

